apiVersion: v1
kind: Namespace
metadata:
  name: rag
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dh-infra
  namespace: rag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dh-infra
  template:
    metadata:
      labels:
        app: dh-infra
    spec:
      containers:
        - name: dh-infra
          image: rohitnx/dh-infra:latest
          ports:
            - containerPort: 8000
          env:
            - name: DH_ADMIN
              value: "dh-admin"
            - name: DH_ADMIN_PORT
              value: "80"
            - name: DH_ADMIN_HEALTH_ENDPOINT
              value: "http://dh-admin:80"

            - name: DH_RAG_QUERY
              value: "rag-query-svc"
            - name: DH_RAG_QUERY_PORT
              value: "8000"
            - name: DH_RAG_QUERY_HEALTH_ENDPOINT
              value: "http://rag-query-svc:8000"

            - name: DH_AVATAR
              value: "dh-switch-avatar-svc"
            - name: DH_AVATAR_PORT
              value: "8000"
            - name: DH_AVATAR_HEALTH_ENDPOINT
              value: "http://dh-switch-avatar-svc:8000/docs"

            - name: OLLAMA_HOST
              value: "http://ollama-svc"
            - name: OLLAMA_PORT
              value: "11434"
            - name: OLLAMA_MODEL
              value: "llama3.2:3b"
            - name: OLLAMA_HEALTH_ENDPOINT
              value: "http://ollama-svc:11434/api/tags"

            - name: TEI_BASE_URL
              value: "http://tei-svc"
            - name: TEI_PORT
              value: "80"
            - name: TEI_HEALTH_ENDPOINT
              value: "http://tei-svc:80/health"

            - name: WEAVIATE_HOST
              value: "http://weaviate-svc"
            - name: WEAVIATE_PORT
              value: "8080"
            - name: WEAVIATE_HEALTH_ENDPOINT
              value: "http://weaviate-svc:8080/v1/.well-known/ready"

            - name: LOG_LEVEL
              value: "DEBUG"
            - name: HTTP_REQUEST_TIMEOUT
              value: "5"
            - name: SERVICE_HEALTH_CHECK_INTERVAL
              value: "10"
            - name: RETRY_WAIT_SECONDS
              value: "2"
            - name: RETRY_MAX_ATTEMPTS
              value: "3"

            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "rag"
            - name: DB_NAME
              value: "rag"
            - name: DB_PASSWORD
              value: "rag123"

            - name: ACTIVE_LLM
              value: "ollama"
            - name: ACTIVE_EMBEDDING
              value: "tei"
            - name: ACTIVE_VECTOR_STORE
              value: "weaviate"
---
apiVersion: v1
kind: Service
metadata:
  name: dh-infra-service
  namespace: rag
spec:
  selector:
    app: dh-infra
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
